### ISSUE TITLE
problem with figure_skating_assessor_datasets.zip extraction

### ISSUE THREAD

**Issue by Rahul-Venugopal** [Bartzi/loans#6]
Hi ,

I am trying to download figure_skating_assessor_datasets.zip file from ( https://bartzi.de/documents/attachment/download?hash_value=8a7b6af749bd5aa0d2c2d3ff0725ebca_24 .) .

Unfortunately I am not able to extract the file and when I check the file is only 8 Bytes in size .

Is there any other link where I can download the dataset ?

**Comment by Bartzi** [comment]
I'm very sorry. An error on my end.
It should work now :smile:

**Comment by Rahul-Venugopal** [comment]
Thanks :)
Now it works (y)
